#ifndef GMCTEventDisplay_H
#define GMCTEventDisplay_H
#include "TGText.h"
////////////////////////////////////////////////////////////////////////////////
//                                                                            //
// GMCTEventDisplay                                                           //
//                                                                            //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

////////////////////////////////////////////////////////////////////////////////
/*  This header was generated by ROMEBuilder. Manual changes above the        *
 * following line will be lost next time ROMEBuilder is executed.             */
/////////////////////////////////////----///////////////////////////////////////

#include "generated/GMCTEventDisplay_Base.h"
#include "TROOT.h"
#include "TCanvas.h"
#include "TLine.h"
#include "TFrame.h"
#include "TStyle.h"
#include <math.h>
#include <TRandom.h> 
#include <TF1.h>
#include "TH2F.h"
#include "TEllipse.h"
#include "TBox.h"
#include "TGraph.h"
#include "TVector.h"
#include "TVector3.h"
class GMCWindow;


class GMCTEventDisplay : public GMCTEventDisplay_Base
{
protected:

private:

   GMCTEventDisplay(const GMCTEventDisplay &c); // not implemented
   GMCTEventDisplay &operator=(const GMCTEventDisplay &c); // not implemented
   TRootEmbeddedCanvas *fCanvas;
   TRootEmbeddedCanvas *fCanvas2;
   TRootEmbeddedCanvas *fCanvas3;

   
   TGraph *gr;   
   TGraph *grw;
   TGraph *grMC;
   
   TH2F *htmp;
   TH2F *hpix;

   TEllipse **el;
   TBox **bx;
   TLine **li;

   Int_t nl;
  
public:
   GMCTEventDisplay(GMCWindow* window = 0):GMCTEventDisplay_Base(window)
   {
   }

   virtual ~GMCTEventDisplay()
   {
   }
   void CellClicked();
   void Init();
   void EndInit();
   void MenuClicked(TGPopupMenu *menu,Long_t param);
   void TabSelected();
   void TabUnSelected();
   void EventHandler();
   void DrawingGeom();
   void Drawing();

   ClassDef(GMCTEventDisplay,0)

};

#endif   // GMCTEventDisplay_H
