////////////////////////////////////////////////////////////////////////////////
//                                                                            //
// GMCTReadMCDataSVX                                                          //
//                                                                            //
// Begin_Html <!--
/*-->

<!--*/
// --> End_Html
//                                                                            //
//                                                                            //
// Please note: The following information is only correct after executing     //
// the ROMEBuilder.                                                           //
//                                                                            //
// This task accesses the following folders :                                 //
//     GeantTrack                                                             //
//     SVXGeantStep                                                           //
//     SVXHit                                                                 //
//                                                                            //
//                                                                            //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

/* Generated header file containing necessary includes                        */
#include "generated/GMCTReadMCDataSVXGeneratedIncludes.h"

////////////////////////////////////////////////////////////////////////////////
/*  This header was generated by ROMEBuilder. Manual changes above the        *
 * following line will be lost next time ROMEBuilder is executed.             */
/////////////////////////////////////----///////////////////////////////////////

#include "generated/GMCAnalyzer.h"
#include "tasks/GMCTReadMCDataSVX.h"
#include "ROMEiostream.h"

// uncomment if you want to include headers of all folders
//#include "GMCAllFolders.h"

#include "generated/GMCConfigToForm.h"
#include "generated/GMCMCRunHeader.h"
#include "generated/GMCGeantTrack.h"
#include "generated/GMCSVXGeantStep.h"
#include "generated/GMCSVXHit.h"

#include "generated/GMCEventLoop.h"

#include "ROGeometryHandle.hh"


ClassImp(GMCTReadMCDataSVX)

//______________________________________________________________________________
void GMCTReadMCDataSVX::Init() {

  //instance the geometry
  fGeometry = GeometrySrvHndl::Instance();
  if(!fGeometry->GetCellHandle())
    fGeometry->makeDetectors();

  _minimumEnergy = GetSP()->GetHitEnergyCut();
}

//______________________________________________________________________________
void GMCTReadMCDataSVX::BeginOfRun()
{
}

//______________________________________________________________________________
void GMCTReadMCDataSVX::Event()
{

  if (gAnalyzer->GetCurrentEventNumber()%100==0 ) { printf("\n ***** ReadMCDataSVX Load event %lld ************************ \n",gAnalyzer->GetCurrentEventNumber()); }
  LoadEvent(gAnalyzer->GetCurrentEventNumber());

  gAnalyzer->SetSVXHitSize(0);
  DefineHitsInSVX();

}

//______________________________________________________________________________
void GMCTReadMCDataSVX::LoadEvent(Int_t nev) {

  fBrDataSvx=gAnalyzer->GetSVXGeantSteps();
  fBrDataTrk=gAnalyzer->GetGeantTracks();
}

//______________________________________________________________________________
void GMCTReadMCDataSVX::DefineHitsInSVX() {

  Int_t NrHits = 0;

  SvxChHitMap hitmap;
  hitmap.clear();
  fillHitMap( hitmap );

  for(SvxChHitMap::const_iterator idchn = hitmap.begin(); idchn != hitmap.end(); ++idchn) {
    unsigned long dchn_id = idchn->first;
//    fGeometry->GetCellHandle()->SelectCellDet(dchn_id);
//    CLHEP::Hep3Vector const& mid   = fGeometry->GetCellHandle()->GetCellCenter();
//    CLHEP::Hep3Vector const& w     = fGeometry->GetCellHandle()->GetCellDirection();

    std::vector<GMCSVXGeantStep *> const& ihits = idchn->second;

    std::map<int,GMCSVXHit *> hitPerTrk;
    std::map<int,GMCSVXHit *>::iterator hitPerTrk_it;

//    std::map<int,TVector3 *> hitEndPerTrk;
//    std::map<int,TVector3 *>::iterator hitEndPerTrk_it;

    for( size_t i=0; i<ihits.size(); i++ ) {

      GMCSVXGeantStep& hit = *(ihits.at(i));

      hitPerTrk_it = hitPerTrk.find(hit.GetfTrackID());
//      hitEndPerTrk_it = hitEndPerTrk.find(hit.GetfTrackID());

      if ( hitPerTrk_it == hitPerTrk.end() ) {
        gAnalyzer->SetSVXHitSize(NrHits+1);
        GMCSVXHit *ahit = gAnalyzer->GetSVXHitAt(NrHits);
        ++NrHits;
        hitPerTrk.insert( std::pair<int,GMCSVXHit *>( hit.GetfTrackID(), ahit ) );
//        hitEndPerTrk.insert( std::pair<int,TVector3 *>( hit.GetfTrackID(), hit.GetfPosEnding() ) );

        ahit->SetfChanId( dchn_id );
        ahit->SetfTrkIDofHit( hit.GetfTrackID() );
        ahit->SetfEntranceX( hit.GetfPos()->X() );
        ahit->SetfEntranceY( hit.GetfPos()->Y() );
        ahit->SetfEntranceZ( hit.GetfPos()->Z() );
        ahit->SetfEntranceMomX( hit.GetfMomentum()->X() );
        ahit->SetfEntranceMomY( hit.GetfMomentum()->Y() );
        ahit->SetfEntranceMomZ( hit.GetfMomentum()->Z() );
        ahit->SetfTotalEnergyLoss( hit.GetfEdep() );
        ahit->SetfGlobalTime( hit.GetfGlobalTime() );
        ahit->SetfToF( hit.GetfProperTime() );

      } else {
        GMCSVXHit *ahit = hitPerTrk_it->second;
        ahit->SetfTotalEnergyLoss( ahit->GetfTotalEnergyLoss() + hit.GetfEdep() );
//        ahit->SetfLength( ahit->GetfLength() + hit.GetfStepLen() );
//        hitEndPerTrk_it->second=hit.GetfPos();
      }

    }

    //FIXME!!! Trackes Pile-up not taken into account!!!

//    for ( hitPerTrk_it=hitPerTrk.begin(); hitPerTrk_it!=hitPerTrk.end(); ++hitPerTrk_it ) {
//      GMCSVXHit *ahit = hitPerTrk_it->second;
//    }

  }

  if (gAnalyzer->GetCurrentEventNumber()%100==0 ) { std::cout<<"nhits "<<gAnalyzer->GetSVXHitSize()<<std::endl; }

}

//______________________________________________________________________________
void GMCTReadMCDataSVX::fillHitMap ( SvxChHitMap& hitmap ) {
  int nentries=fBrDataSvx->GetEntries();
  for (int istep=0;istep<nentries;istep++) {
    GMCSVXGeantStep *aStep = (GMCSVXGeantStep *)fBrDataSvx->At(istep);
    if( (aStep->GetfEdep()-aStep->GetfNoIEdep())<_minimumEnergy ) continue; // Skip steps with very low energy deposition
    unsigned long unqChId = fGeometry->GetROChanHandle()->computeDet(aStep->GetfChamberNr(),aStep->GetfChannelNr());
    hitmap[unqChId].push_back(aStep);
  }
}

//______________________________________________________________________________
void GMCTReadMCDataSVX::EndOfRun()
{
}

//______________________________________________________________________________
void GMCTReadMCDataSVX::Terminate()
{
}


