////////////////////////////////////////////////////////////////////////////////
//                                                                            //
// GMCTReadMCDataPHCV                                                         //
//                                                                            //
// Begin_Html <!--
/*-->

<!--*/
// --> End_Html
//                                                                            //
//                                                                            //
//                                                                            //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

/* Generated header file containing necessary includes                        */
#include "generated/GMCTReadMCDataPHCVGeneratedIncludes.h"

////////////////////////////////////////////////////////////////////////////////
/*  This header was generated by ROMEBuilder. Manual changes above the        *
 * following line will be lost next time ROMEBuilder is executed.             */
/////////////////////////////////////----///////////////////////////////////////

#include "generated/GMCAnalyzer.h"
#include "tasks/GMCTReadMCDataPHCV.h"
#include "ROMEiostream.h"

// uncomment if you want to include headers of all folders
//#include "GMCAllFolders.h"


ClassImp(GMCTReadMCDataPHCV)

//______________________________________________________________________________
void GMCTReadMCDataPHCV::Init()
{
}

//______________________________________________________________________________
void GMCTReadMCDataPHCV::BeginOfRun()
{
}

//______________________________________________________________________________
void GMCTReadMCDataPHCV::Event()
{
}

//______________________________________________________________________________
void GMCTReadMCDataPHCV::EndOfRun()
{
}

//______________________________________________________________________________
void GMCTReadMCDataPHCV::Terminate()
{
}

