////////////////////////////////////////////////////////////////////////////////
//                                                                            //
// GMCTCalibrations                                                           //
//                                                                            //
// Begin_Html <!--
/*-->

<!--*/
// --> End_Html
//                                                                            //
//                                                                            //
//                                                                            //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

/* Generated header file containing necessary includes                        */
#include "generated/GMCTCalibrationsGeneratedIncludes.h"

////////////////////////////////////////////////////////////////////////////////
/*  This header was generated by ROMEBuilder. Manual changes above the        *
 * following line will be lost next time ROMEBuilder is executed.             */
/////////////////////////////////////----///////////////////////////////////////

#include "generated/GMCAnalyzer.h"
#include "tasks/GMCTCalibrations.h"
#include "ROMEiostream.h"

// uncomment if you want to include headers of all folders
//#include "GMCAllFolders.h"


ClassImp(GMCTCalibrations)

//______________________________________________________________________________
void GMCTCalibrations::Init()
{
}

//______________________________________________________________________________
void GMCTCalibrations::BeginOfRun()
{
}

//______________________________________________________________________________
void GMCTCalibrations::Event()
{
}

//______________________________________________________________________________
void GMCTCalibrations::EndOfRun()
{
}

//______________________________________________________________________________
void GMCTCalibrations::Terminate()
{
}

