// Author: Chiri Claudio

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
// GMCTGMCMain                                                                //
//                                                                            //
// Begin_Html <!--
/*-->

Description:
<p>
Main task. This task does common initialization for all the tasks.
</p>

<!--*/
// --> End_Html
//                                                                            //
// The event methods have been written by Chiri Claudio.                      //
//                                                                            //
//                                                                            //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

/* Generated header file containing necessary includes                        */
#include "generated/GMCTGMCMainGeneratedIncludes.h"

////////////////////////////////////////////////////////////////////////////////
/*  This header was generated by ROMEBuilder. Manual changes above the        *
 * following line will be lost next time ROMEBuilder is executed.             */
/////////////////////////////////////----///////////////////////////////////////

#include "generated/GMCAnalyzer.h"
#include "tasks/GMCTGMCMain.h"
#include "ROMEiostream.h"

// uncomment if you want to include headers of all folders
//#include "GMCAllFolders.h"


ClassImp(GMCTGMCMain)

//______________________________________________________________________________
void GMCTGMCMain::Init()
{
}

//______________________________________________________________________________
void GMCTGMCMain::BeginOfRun() {



}

//______________________________________________________________________________
void GMCTGMCMain::Event()
{
}

//______________________________________________________________________________
void GMCTGMCMain::EndOfRun()
{
}

//______________________________________________________________________________
void GMCTGMCMain::Terminate()
{
}

