export WAVEDATA_DIR=WaveData
export LD_LIBRARY_PATH=$WAVEDATA_DIR:${WAVEDATA_DIR}/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=${ROOTSYS}/lib:$LD_LIBRARY_PATH
#export LD_LIBRARY_PATH=/opt/root-6.14.02/lib:$LD_LIBRARY_PATH
